### PR TITLE
Mac OS support

### PR DESCRIPTION
**Pull request by jensstigaard**
Added mac OS support. 

Included NDI library for Mac, updated bindings and tested. It worked.

Also updated readme.

### CODE REVIEW

**Comment by 2xAA** [comment]
@sparkpunkd would we be able to get this merged soon? (also #2)

**Comment by kyelewis** [comment]
Thanks for this great work @jensstigaard on the darwin support - I grabbed your branch to test on an electron app on MacOS and the find and video receive works some of the time.

Unfortunately sometimes the process crashes after an invalid 0x0 video resolution- I see there is a check in the receive code for this condition, but things crash before it bubbles up to a promise rejection.

Hope to have some time to help investigate why next week... but wanted to say thanks for the great work and starting point!

**Comment by jensstigaard** [comment]
> Thanks for this great work @jensstigaard on the darwin support - I grabbed your branch to test on an electron app on MacOS and the find and video receive works some of the time.
> 
> Unfortunately sometimes the process crashes after an invalid 0x0 video resolution- I see there is a check in the receive code for this condition, but things crash before it bubbles up to a promise rejection.
> 
> Hope to have some time to help investigate why next week... but wanted to say thanks for the great work and starting point!

Hi Kyle, any news on the issue you are experiencing?

**Comment by jensstigaard** [comment]
> @jensstigaard I cant make an issue or anything on your fork.... just wanted to say thanks for all the work on this! much appreciated! I was just about to start looking at forking this and updating it when I thought I'd better check the network graph!

You are welcome. Hopefully at some point we can have all the updated code merged into the main repo...

**Comment by jensstigaard** [comment]
> @jensstigaard things work perfectly on macosx but I try and just install the module on debian and I get failures...

Hi Dan
Just to let you know, this pull request is regarding support for MacOS, not Linux. 
There is another pull request specifically regarding Linux support.
Please visit https://github.com/Streampunk/grandiose/pull/2
I think it is more appropriate to post your concerns in that thread.

**Comment by jensstigaard** [comment]
> hey @jensstigaard - that fork works fine for linux - looks like something changed in your fork of that fork

That sounds strange. Can you provide any error messages? 
There's a lot of things updated in my repo - cpp header files, change of nullptr to NULL in napi module, extended commenting, and more.
So it is hard to say what you be the root cause.
I have not tested on Linux myself, and I have no plan to do so ATM.

**Comment by Julusian** [comment]
Support for macos has been merged in #18

**Pull request closed without merging**
